export const AUTH_SIGN_IN_SUCCESS = 'AUTH_SIGN_IN_SUCCESS';
export const AUTH_SIGN_IN_FAILURE = 'AUTH_SIGN_IN_FAILURE';

export const DRAGON_LIST_SET = 'DRAGON_LIST_SET';
export const DRAGON_LIST_FAILURE = 'DRAGON_LIST_FAILURE';

export const DRAGON_SET = 'DRAGON_SET';
export const DRAGON_RESET = 'DRAGON_RESET';
export const DRAGON_UPDATE_SUCCESS = 'DRAGON_UPDATE_SUCCESS';
export const DRAGON_UPDATE_FAILURE = 'DRAGON_UPDATE_FAILURE';
export const DRAGON_CREATE_SUCCESS = 'DRAGON_CREATE_SUCCESS';
export const DRAGON_CREATE_FAILURE = 'DRAGON_CREATE_FAILURE';
